### ISSUE TITLE
Plist values automatically revert after 5-10 seconds

### ISSUE THREAD

**Issue by alse** [wollardj/node-simple-plist#44]
I'm trying to update `/Users/username/Library/Preferences/com.apple.ncprefs.plist` but the change only sticks for 5-10 seconds before being reverted to the original value.

Can this caused by node-simple-plist, or is it something else? I'm running it on Big Sur

```
const plist = require('simple-plist')
const PATH = '/Users/username/Library/Preferences/com.apple.ncprefs.plist'

const data = plist.readFileSync(PATH)
data.apps[2].flags = newFlagsValue // I verified that the new value is valid
plist.writeBinaryFileSync(PATH, data)
```

**Comment by wollardj** [comment]
That's actually caused by the CFPreferences daemon (cfprefsd). PlistBuddy would have the same issue. If you want to make modifications to files like these, you can use the `defaults` cli tool.

Here's a post from Greg Neagle from back in 2013 talking about the issue when it was being recognized by the mac admin community: https://www.jamf.com/jamf-nation/discussions/9052/default-dock-for-mavericks#responseChild49180

**Comment by alse** [comment]
Ahh thank you @wollardj!
